#!/bin/bash
# {{{ Useful URLs 
#
# Useful documentation.
#   https://miktex.org/howto/install-miktex-unx
#   https://linuxize.com/post/how-to-install-ruby-on-debian-9/
#
# -------------------------------------------------------------------------- }}}
# {{{ Define products to install. 
#
# Notes:
#   1) 0 == false && 1 == true ... Duh!
#   2) Options are listed alphabetically only because I scan them faster.
#
# {{{ Products to install. 

bashrcFlag=0
emendFlag=0  
echoConfigFlag=0
gitconfigFlag=0
hostsFlag=0
miktexFlag=0
osUpdateFlag=0
profileFlag=0
rbenvFlag=0
resolvFlag=0
rustFlag=0
rustProgramsFlag=0
texliveFlag=0
ubuntuFlag=0
wslFlag=0
xWindowsFlag=0

# -------------------------------------------------------------------------- }}}
# {{{ Other variables used during product installation. 

cloneRoot=$HOME/git
gitEmail="gary.a.howard@mac.com"
gitName="Traap"
miktexGpgKey='D6BC243565B2087BC3F897C9277A7293F59E4889'
miktexSource='ubuntu focal universe'
rubyVersion='2.7.2'

# -------------------------------------------------------------------------- }}}
# -------------------------------------------------------------------------- }}}
