#!/bin/bash
# {{{ Useful URLs
#
# Useful documentation.
#   https://miktex.org/howto/install-miktex-unx
#   https://linuxize.com/post/how-to-install-ruby-on-debian-9/
#
# -------------------------------------------------------------------------- }}}
# {{{ Notes
#
# Notes:
#   1) Options are listed alphabetically only because I scan them faster.
#
# -------------------------------------------------------------------------- }}}
# {{{ Define Products to install.

bashrcFlag=false
dbeaverFlag=false
emendFlag=false
echoConfigFlag=false
gitBashPromptFlag=false
gitconfigFlag=false
graphVizFlag=false
hostsFlag=false
javaJreFlag=false
miktexFlag=false
muttFlag=false
osUpdateFlag=false
profileFlag=false
rbenvFlag=false
resolvFlag=false
rustFlag=false
rustProgramsFlag=false
texliveFlag=false
tldrFlag=false
ubuntuFlag=false
wslFlag=false
xWindowsFlag=false

# -------------------------------------------------------------------------- }}}
# {{{ Other variables used during product installation.

cloneRoot=$HOME/git
gitEmail="gary.a.howard@mac.com"
gitName="Traap"
miktexGpgKey='D6BC243565B2087BC3F897C9277A7293F59E4889'
miktexSource='ubuntu focal universe'
rubyVersion='3.2.2'

# -------------------------------------------------------------------------- }}}
