#!/bin/bash

# Update OS
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y autoremove

# VcXsrv for Copy & Paste
# Note: Use Power Shell with Administrator rights.
# choco install -y vcxsrv

# Install xsel for Copy and Paste
sudo apt-get install -y xsel
sudo apt-get install -y vim-gtk

# Install neovim
sudo apt-get install -y neovim

# Install git
sudo apt-get install -y git

# Make and c/c++ compiler
sudo apt-get install -y make
sudo apt-get install -y gcc

# Keyserver, CRL, and OCSP access for GnuPG
suso apt-get install -y dirmngr

# MikTeX
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
echo "deb http://miktex.org/download/debian stretch universe" | sudo tee /etc/apt/sources.list.d/miktex.list
sudo apt-get install -y apt-transport-https
sudo apt-get update
sudo apt-get install miktex

# Install rbenv
# See: https://linuxize.com/post/how-to-install-ruby-on-debian-9/
sudo apt-get update -y
sudo apt install git curl libssl-dev libreadline-dev zlib1g-dev autoconf bison \
     build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev \
     libssl-dev libgdbm-dev
     
curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -

# Add $HJME/.rbenv/bin to your path.
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
source ~/.bashrc

# Install ruby
rbenv install 2.6.3
rbenv global 2.6.3

# Install Ruby bundler
sudo apt-get install -y ruby-bundler
gem install bundler

# Clone and build emend. 
mkdir git
cd git
clone http://github.com/Traap/emend.git
cd emend
bundle install
bundle exec rake
bundle exec rake install
rake --format documentation

# Clone and emend this system. 
cd ..
clone http://github.com/Traap/emend-computer.git
cd emend-computer

# Personalize Traap's environment.
# Note:  Only linux commands are ran when run from a wsl distro.
emend --verbose --nodryrun --bundle debian 
