#!/bin/bash

# Update OS
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y autoremove

# Redirect your linux user to your windows user.
# vi /etc/passwd
# gary:x:1000:1000:,,,:/mnt/c/Users/gary:/bin/bash

# VcXsrv for Copy & Paste
# Note: Use Power Shell with Administrator rights.
# choco install -y vcxsrv

# Install xsel for Copy and Paste
sudo apt-get install -y xsel
sudo apt-get install -y vim-gtk

# Install git
# sudo apt-get install -y git

# Make and c/c++ compiler
sudo apt-get install -y make
sudo apt-get install -y gcc

# Keyserver, CRL, and OCSP access for GnuPG
suso apt-get install -y dirmngr

# MikTeX
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
echo "deb http://miktex.org/download/debian stretch universe" | sudo tee /etc/apt/sources.list.d/miktex.list
sudo apt-get install -y apt-transport-https
sudo apt-get update
sudo apt-get install miktex

# Install ruby and required gems
# Is sudo really needed?
sudo apt-get install -y ruby-full
sudo gem install bundler

# Clone and build emend. 
mkdir git
cd git
clone http://github.com/Traap/emend.git
cd emend
bundle install
bundle exec rake
bundle exec rake install
rake --format documentation

# Clone and emend this system. 
cd ..
clone http://github.com/Traap/emend-computer.git
cd emend-computer

# Windows setup.
# Note:  Only linux commands are ran when run from a wsl distro.
emend --verbose --nodryrun --bundle debian 
